# Generated by Django 5.2.6 on 2025-09-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='date_realisation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='operation',
            name='id_operation',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
