# Generated by Django 5.2.6 on 2025-09-30 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_operation_date_paiement_operation_date_realisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='devis_cree',
            field=models.BooleanField(default=False, verbose_name='Devis créé'),
        ),
        migrations.AddField(
            model_name='operation',
            name='devis_date_envoi',
            field=models.DateField(blank=True, null=True, verbose_name='Date envoi devis'),
        ),
        migrations.AddField(
            model_name='operation',
            name='devis_statut',
            field=models.CharField(blank=True, choices=[('en_attente', 'En attente de réponse'), ('accepte', 'Devis accepté'), ('refuse', 'Devis refusé'), ('relance', 'À relancer')], max_length=20, null=True, verbose_name='Statut du devis'),
        ),
        migrations.AddField(
            model_name='operation',
            name='mode_paiement',
            field=models.CharField(choices=[('comptant', 'Comptant'), ('echelonne', 'Échelonné')], default='comptant', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name="Numéro d'échéance")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement réel')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('retard', 'En retard')], default='en_attente', max_length=20)),
                ('ordre', models.IntegerField(default=1)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='core.operation')),
            ],
            options={
                'verbose_name': 'Échéance de paiement',
                'verbose_name_plural': 'Échéances de paiement',
                'ordering': ['ordre'],
            },
        ),
    ]
