# Generated by Django 5.2.6 on 2025-10-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_operation_devis_cree_operation_devis_date_envoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date_realisation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réalisation'),
        ),
    ]
