# Generated by Django 5.2.6 on 2025-10-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_operation_date_paiement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echeance',
            name='date_paiement',
        ),
        migrations.RemoveField(
            model_name='echeance',
            name='statut',
        ),
        migrations.AddField(
            model_name='echeance',
            name='paye',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
    ]
