# Generated by Django 5.2.6 on 2025-10-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_echeance_date_paiement_remove_echeance_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='devis_date_reponse',
            field=models.DateField(blank=True, null=True, verbose_name='Date réponse client'),
        ),
    ]
