# Generated by Django 5.2.6 on 2025-10-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_operation_devis_date_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='commentaires',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaires / Notes'),
        ),
    ]
