# Generated by Django 5.2.6 on 2025-10-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_operation_commentaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date_prevue',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date prévue d'intervention"),
        ),
    ]
