# Generated by Django 5.2.6 on 2025-10-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_operation_date_prevue'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='planning_mode',
            field=models.CharField(choices=[('a_planifier', 'À planifier'), ('replanifier', 'Replanifier'), ('deja_realise', 'Déjà réalisé')], default='a_planifier', max_length=20, verbose_name='Mode de planification'),
        ),
    ]
