# Generated by Django 5.2.6 on 2025-10-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_operation_planning_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='avec_devis',
            field=models.BooleanField(default=False, verbose_name='Opération avec devis'),
        ),
        migrations.AddField(
            model_name='operation',
            name='devis_historique_numeros',
            field=models.TextField(blank=True, help_text='Liste JSON des anciens numéros de devis (en cas de refus et nouveau devis)', null=True, verbose_name='Historique des numéros de devis'),
        ),
        migrations.AddField(
            model_name='operation',
            name='devis_notes',
            field=models.TextField(blank=True, help_text='Notes qui apparaîtront sur le PDF du devis', null=True, verbose_name='Notes du devis'),
        ),
        migrations.AddField(
            model_name='operation',
            name='devis_validite_jours',
            field=models.IntegerField(default=30, help_text='Nombre de jours de validité du devis', verbose_name='Validité du devis (jours)'),
        ),
        migrations.AddField(
            model_name='operation',
            name='facture_date_emission',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'émission de la facture"),
        ),
        migrations.AddField(
            model_name='operation',
            name='facture_generee',
            field=models.BooleanField(default=False, verbose_name='Facture générée'),
        ),
        migrations.AddField(
            model_name='operation',
            name='facture_notes',
            field=models.TextField(blank=True, help_text='Notes qui apparaîtront sur le PDF de la facture', null=True, verbose_name='Notes de la facture'),
        ),
        migrations.AddField(
            model_name='operation',
            name='numero_devis',
            field=models.CharField(blank=True, help_text='Format: DEV-2025-001', max_length=20, null=True, unique=True, verbose_name='Numéro de devis'),
        ),
        migrations.AddField(
            model_name='operation',
            name='numero_facture',
            field=models.CharField(blank=True, help_text='Format: FAC-2025-001', max_length=20, null=True, unique=True, verbose_name='Numéro de facture'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='devis_date_envoi',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'envoi du devis"),
        ),
        migrations.AlterField(
            model_name='operation',
            name='devis_date_reponse',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réponse du client'),
        ),
    ]
