# Generated by Django 5.2.6 on 2025-11-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_operation_avec_devis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='prix_unitaire_ht',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire HT en euros', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Quantité (ex: 2, 1.5, 10)', max_digits=10),
        ),
        migrations.AddField(
            model_name='intervention',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Taux de TVA en %', max_digits=5),
        ),
        migrations.AddField(
            model_name='intervention',
            name='unite',
            field=models.CharField(choices=[('unite', 'Unité'), ('forfait', 'Forfait'), ('heure', 'Heure'), ('jour', 'Jour'), ('m2', 'm²'), ('ml', 'Mètre linéaire')], default='forfait', help_text='Unité de mesure', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Total HT de la ligne (quantité × prix unitaire HT)', max_digits=10),
        ),
    ]
