# Generated by Django 5.2.6 on 2025-11-05 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_intervention_prix_unitaire_ht_intervention_quantite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise / Raison sociale")),
                ('forme_juridique', models.CharField(blank=True, choices=[('auto_entrepreneur', 'Auto-entrepreneur / Micro-entreprise'), ('eurl', 'EURL'), ('sarl', 'SARL'), ('sas', 'SAS'), ('sasu', 'SASU'), ('ei', 'Entreprise Individuelle'), ('autre', 'Autre')], max_length=50, verbose_name='Forme juridique')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse du siège social')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('siret', models.CharField(blank=True, max_length=14, verbose_name='N° SIRET')),
                ('rcs', models.CharField(blank=True, help_text='Ex: RCS Paris 123 456 789', max_length=100, verbose_name='N° RCS + Ville')),
                ('code_ape', models.CharField(blank=True, max_length=10, verbose_name='Code APE/NAF')),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capital social (€)')),
                ('tva_intracommunautaire', models.CharField(blank=True, max_length=20, verbose_name='N° TVA intracommunautaire')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone professionnel')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('assurance_decennale_nom', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'assureur")),
                ('assurance_decennale_numero', models.CharField(blank=True, max_length=100, verbose_name='N° de police')),
                ('assurance_decennale_validite', models.DateField(blank=True, null=True, verbose_name='Date de validité')),
                ('qualifications', models.TextField(blank=True, help_text='Ex: RGE, Qualibat, etc.', verbose_name='Qualifications / Certifications')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name="Logo de l'entreprise")),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC/SWIFT')),
                ('mentions_legales_devis', models.TextField(blank=True, help_text='Texte qui apparaîtra en bas du devis (conditions de paiement, pénalités de retard, etc.)', verbose_name='Mentions légales sur le devis')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_entreprise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil entreprise',
                'verbose_name_plural': 'Profils entreprise',
            },
        ),
    ]
