# Generated by Django 5.2.6 on 2025-11-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profilentreprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilentreprise',
            name='logo',
        ),
    ]
