# Generated by Django 5.2.6 on 2025-11-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_profilentreprise_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeance',
            name='facture_date_emission',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'émission facture"),
        ),
        migrations.AddField(
            model_name='echeance',
            name='facture_generee',
            field=models.BooleanField(default=False, verbose_name='Facture générée'),
        ),
        migrations.AddField(
            model_name='echeance',
            name='facture_type',
            field=models.CharField(blank=True, choices=[('globale', 'Facture globale'), ('acompte', "Facture d'acompte"), ('solde', 'Facture de solde')], max_length=20, null=True, verbose_name='Type de facture'),
        ),
        migrations.AddField(
            model_name='echeance',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de facture'),
        ),
    ]
