# Generated by Django 5.2.6 on 2025-11-19 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_echeance_facture_date_emission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='devis_cree',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='devis_date_envoi',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='devis_date_reponse',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='devis_historique_numeros',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='devis_notes',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='devis_statut',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='devis_validite_jours',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='facture_date_emission',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='facture_generee',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='facture_notes',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='numero_devis',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='numero_facture',
        ),
        migrations.AlterField(
            model_name='profilentreprise',
            name='mentions_legales_devis',
            field=models.TextField(blank=True, help_text='Texte qui apparaîtra en bas du devis', verbose_name='Mentions légales sur le devis'),
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devis', models.CharField(help_text='Format: DEVIS-2025-U1-00001', max_length=30, unique=True, verbose_name='Numéro de devis')),
                ('version', models.PositiveIntegerField(default=1, help_text='1, 2, 3... (incrémenté automatiquement)', verbose_name='Version du devis')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_envoi', models.DateField(blank=True, null=True, verbose_name="Date d'envoi au client")),
                ('date_reponse', models.DateField(blank=True, null=True, verbose_name='Date de réponse du client')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='brouillon', max_length=20, verbose_name='Statut du devis')),
                ('notes', models.TextField(blank=True, help_text='Notes qui apparaîtront sur le PDF', verbose_name='Notes du devis')),
                ('validite_jours', models.IntegerField(default=30, help_text='Nombre de jours de validité', verbose_name='Validité (jours)')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_set', to='core.operation')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['version'],
                'unique_together': {('operation', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité')),
                ('unite', models.CharField(choices=[('unite', 'Unité'), ('forfait', 'Forfait'), ('heure', 'Heure'), ('jour', 'Jour'), ('m2', 'm²'), ('ml', 'Mètre linéaire')], default='forfait', max_length=20, verbose_name='Unité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT (€)')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Calculé automatiquement (quantité × prix unitaire HT)', max_digits=10, verbose_name='Total HT')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'ordering': ['ordre'],
            },
        ),
    ]
