# Generated by Django 5.2.6 on 2025-11-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_operation_devis_cree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('pret', 'Prêt (PDF généré)'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='brouillon', max_length=20, verbose_name='Statut du devis'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='statut',
            field=models.CharField(choices=[('en_attente_devis', 'En attente devis'), ('a_planifier', 'À planifier'), ('planifie', 'Planifié'), ('en_cours', '🔵 En cours'), ('a_traiter', '🟠 À traiter'), ('realise', 'Réalisé'), ('paye', 'Payé'), ('devis_refuse', 'Devis refusé / Opération annulée')], default='en_attente_devis', max_length=20),
        ),
    ]
