# Generated by Django 5.2.6 on 2025-11-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_devis_statut_alter_operation_statut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ['ordre', 'date_prevue'], 'verbose_name': 'Intervention', 'verbose_name_plural': 'Interventions'},
        ),
        migrations.AddField(
            model_name='intervention',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Notes libres sur cette intervention', verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='date_prevue',
            field=models.DateTimeField(blank=True, help_text='Date et heure planifiées pour cette intervention', null=True, verbose_name='Date prévue'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='date_realisation',
            field=models.DateTimeField(blank=True, help_text="Rempli automatiquement quand l'intervention est marquée comme réalisée", null=True, verbose_name='Date de réalisation'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='realise',
            field=models.BooleanField(default=False, help_text="Cocher si l'intervention a été effectuée", verbose_name='Réalisée'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.TextField(verbose_name="Description de l'intervention"),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Total HT de la ligne (quantité × prix unitaire HT)', max_digits=10, verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='ordre',
            field=models.PositiveIntegerField(default=999, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='prix_unitaire_ht',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire HT en euros', max_digits=10, null=True, verbose_name='Prix unitaire HT (€)'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Quantité (ex: 2, 1.5, 10)', max_digits=10, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Taux de TVA en %', max_digits=5, verbose_name='Taux TVA (%)'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='unite',
            field=models.CharField(choices=[('unite', 'Unité'), ('forfait', 'Forfait'), ('heure', 'Heure'), ('jour', 'Jour'), ('m2', 'm²'), ('ml', 'Mètre linéaire')], default='forfait', help_text='Unité de mesure', max_length=20, verbose_name='Unité'),
        ),
    ]
