# Generated by Django 5.2.6 on 2025-11-23 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_intervention_options_intervention_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ['ordre'], 'verbose_name': 'Intervention', 'verbose_name_plural': 'Interventions'},
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='date_prevue',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='date_realisation',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='realise',
        ),
        migrations.AlterField(
            model_name='intervention',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='prix_unitaire_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire HT (€)'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Taux TVA (%)'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='unite',
            field=models.CharField(choices=[('unite', 'Unité'), ('forfait', 'Forfait'), ('heure', 'Heure'), ('jour', 'Jour'), ('m2', 'm²'), ('ml', 'Mètre linéaire')], default='forfait', max_length=20, verbose_name='Unité'),
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1, verbose_name='Numéro du passage')),
                ('date_prevue', models.DateTimeField(blank=True, help_text='Date et heure planifiées pour ce passage', null=True, verbose_name='Date prévue')),
                ('date_realisation', models.DateTimeField(blank=True, help_text='Rempli automatiquement quand marqué comme réalisé', null=True, verbose_name='Date de réalisation')),
                ('realise', models.BooleanField(default=False, verbose_name='Réalisé')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire sur ce passage')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='core.intervention')),
            ],
            options={
                'verbose_name': 'Passage',
                'verbose_name_plural': 'Passages',
                'ordering': ['numero', 'date_prevue'],
            },
        ),
    ]
