# Generated by Django 5.2.6 on 2025-11-23 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_intervention_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1, verbose_name='Numéro du passage')),
                ('date_prevue', models.DateTimeField(blank=True, null=True, verbose_name='Date prévue du passage')),
                ('date_realisation', models.DateTimeField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('realise', models.BooleanField(default=False, verbose_name='Passage réalisé')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire sur ce passage')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='core.operation')),
            ],
            options={
                'verbose_name': 'Passage',
                'verbose_name_plural': 'Passages',
                'ordering': ['numero', 'date_prevue'],
            },
        ),
    ]
