# Generated by Django 5.2.6 on 2025-11-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_passageoperation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passage',
        ),
    ]
