# Generated by Django 5.2.6 on 2025-11-23 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_passage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passageoperation',
            options={'ordering': ['date_prevue', 'created_at'], 'verbose_name': "Passage d'opération", 'verbose_name_plural': "Passages d'opération"},
        ),
        migrations.AddField(
            model_name='passageoperation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 23, 22, 2, 17, 260202)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passageoperation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='passageoperation',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passageoperation',
            name='date_prevue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passageoperation',
            name='date_realisation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passageoperation',
            name='numero',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='passageoperation',
            name='realise',
            field=models.BooleanField(default=False),
        ),
    ]
